#!/usr/bin/env lua
-- -*- lua -*-
--require("strict")
local luaV   = _VERSION:gsub("Lua ","")
package.path = "/opt/apps/luatools/luatools/share/" .. luaV .. "/?.lua;" .. package.path
package.path = "./src/?.lua;" .. package.path

function string:split(pat)
   local st, g = 1, self:gmatch("()("..pat..")")
   local function getter(self, segs, seps, sep, cap1, ...)
      st = sep and seps + #sep
      return self:sub(segs, (seps or 0) - 1), cap1 or sep, ...
   end
   local function splitter(self)
      if st then return getter(self, st, g()) end
   end
   return splitter, self
end



function main()
   local a = {}
   for _,v in ipairs(arg) do
      local result=""
      for path in package.path:split(";") do
         local s = path:gsub("?",v)
         local f = io.open(s,"r")
         if (f) then
            f:close()
            a[#a+1] = s
            result = s
            break;
         end
      end
   end 
   print (table.concat(a," "))
end

main()
