#!/bin/bash
# -*- shell-script -*-
# System-wide .bashrc file for interactive bash(1) shells.

# System-wide .profile for sh(1)

if [ -z "$__PATH_HELPER" -a -x /usr/libexec/path_helper ]; then
   export __PATH_HELPER=1
   eval `/usr/libexec/path_helper -s`
fi

########################################################################
#   Begin Shell Startup Debug
########################################################################

    # Source the shell startup debug indent functions *.SH
    if ! shopt -q login_shell; then
      for i in /etc/profile.d/*.SH; do
        if [ -r $i ]; then
          . $i
        fi
      done
      unset i
      DBG_INDENT_FUNC first  # force the creation of log file if $SHELL_STARTUP_DEBUG > 2
    fi

    MY_NAME="/etc/bashrc"
    DBG_ECHO "$DBG_INDENT$MY_NAME{"

    DBG_INDENT_FUNC up

    if ! shopt -q login_shell; then
      for i in /etc/profile.d/*.sh; do
	DBG_RESET_DELTA_TIMER  # Reset the delta timer so that the time on the
                               # 1st first file sourced is just for it.
        if [ -r $i ]; then
          DBG_ECHO "$DBG_INDENT$i{"
          . $i
          DBG_ECHO "$DBG_INDENT}"
        fi
      done
      unset i
    fi

    DBG_INDENT_FUNC down

    ###################################################################
    # System-wide .bashrc file for interactive bash(1) shells.
    # if [ -z "$PS1" ]; then
    #   return
    # fi  
    ###################################################################

    # To enable the settings / commands in this file for login shells as well,
    # this file has to be sourced in /etc/profile.

    # If not running interactively, don't do anything
    if [ -z "$PS1" ]; then
      DBG_ECHO "$DBG_INDENT}"
      return
    fi  

########################################################################
#   End Shell Startup Debug
########################################################################

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

[ "$PS1" = "\\s-\\v\\\$ " ] &&  PS1='\h:\W \u\$ '


# Tell the terminal about the working directory at each prompt.
if [ "$TERM_PROGRAM" == "Apple_Terminal" ] && [ -z "$INSIDE_EMACS" ]; then
    update_terminal_cwd() {
        # Identify the directory using a "file:" scheme URL,
        # including the host name to disambiguate local vs.
        # remote connections. Percent-escape spaces.
	local SEARCH=' '
	local REPLACE='%20'
	local PWD_URL="file://$HOSTNAME${PWD//$SEARCH/$REPLACE}"
	printf '\e]7;%s\a' "$PWD_URL"
    }
    PROMPT_COMMAND="update_terminal_cwd; $PROMPT_COMMAND"
fi
								    
########################################################################
#   Begin Shell Startup Debug
########################################################################

   DBG_ECHO "$DBG_INDENT}"

########################################################################
#   End Shell Startup Debug
########################################################################
