#!/bin/bash
# -*- shell-script -*-
# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

if [ -z "$__PATH_HELPER" -a -x /usr/libexec/path_helper ]; then
   export __PATH_HELPER=1
   eval `/usr/libexec/path_helper -s`
fi

########################################################################
#   Begin Shell Startup Debug
########################################################################

    if [ -d /etc/profile.d ]; then
      for i in /etc/profile.d/*.SH; do
        if [ -r $i ]; then
          . $i
        fi
      done
      unset i
    fi

    DBG_INDENT_FUNC first # force the creation of log file
    DBG_INDENT_FUNC init
    MY_NAME="/etc/profile"
    DBG_ECHO "$DBG_INDENT$MY_NAME{"

    DBG_INDENT_FUNC up

    if [ -d /etc/profile.d ]; then
      for i in /etc/profile.d/*.sh; do
        DBG_INDENT_FUNC clear  # This clears the echo function/alias if it exists
        if [ -r $i ]; then
          DBG_ECHO "$DBG_INDENT$i{"
          . $i
          DBG_ECHO "$DBG_INDENT}"
        fi
      done
      unset i
    fi  

########################################################################
#   End Shell Startup Debug
########################################################################

if [ "${BASH-no}" != "no" -a -f /etc/bashrc ]; then
   . /etc/bashrc
fi

########################################################################
#   Begin Shell Startup Debug
########################################################################

    DBG_INDENT_FUNC down
    DBG_ECHO "$DBG_INDENT}"

########################################################################
#   End Shell Startup Debug
########################################################################
