#!/bin/bash
# -*- shell-script -*-
# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

########################################################################
#   Begin Shell Startup Debug
########################################################################
    if [ -d /etc/profile.d ]; then
      for i in /etc/profile.d/*.SH; do
        if [ -r $i ]; then
          . $i
        fi
      done
      unset i
    fi

    DBG_INDENT_FUNC init  # force the creation of log file if $SHELL_STARTUP_DEBUG > 2
    MY_NAME="/etc/profile"
    DBG_ECHO "$DBG_INDENT$MY_NAME{"

    DBG_INDENT_FUNC up

    ###################################################################
    # if [ -d /etc/profile.d ]; then
    #   for i in /etc/profile.d/*.sh; do
    #     if [ -r $i ]; then
    #       . $i
    #     fi
    #   done
    #   unset i
    # fi    
    ###################################################################


    DBG_RESET_DELTA_TIMER  # Reset the delta timer so that the time on the
                           # 1st first file sourced is just for it.
    for i in /etc/profile.d/*.sh; do
      if [ -r $i ]; then
        DBG_ECHO "$DBG_INDENT$i{"
        . $i
        DBG_ECHO "$DBG_INDENT}"
      fi
    done
    unset i

########################################################################
#   End Shell Startup Debug
########################################################################

if [ "$PS1" ]; then
  if [ "$BASH" ] && [ "$BASH" != "/bin/sh" ]; then
    # The file bash.bashrc already sets the default PS1.
    # PS1='\h:\w\$ '
    if [ -f /etc/bash.bashrc ]; then
      . /etc/bash.bashrc
    fi
  else
    if [ "`id -u`" -eq 0 ]; then
      PS1='# '
    else
      PS1='$ '
    fi
  fi
fi

########################################################################
#   Begin Shell Startup Debug
########################################################################

    DBG_INDENT_FUNC down
    DBG_ECHO "$DBG_INDENT}"

########################################################################
#   End Shell Startup Debug
########################################################################

# The default umask is now handled by pam_umask.
# See pam_umask(8) and /etc/login.defs.

