#!/bin/zsh
# -*- shell-script -*-

########################################################################
#   Begin Shell Startup Debug
########################################################################

     DBG_INDENT_FUNC init

     MY_NAME="/etc/zlogout"
     DBG_ECHO "$DBG_INDENT$MY_NAME{"

     DBG_INDENT_FUNC up

     for i in /etc/profile.d/*.sh.fini; do
       if [ -r $i ]; then
         DBG_ECHO "$DBG_INDENT$i{"
         . $i
         DBG_ECHO "$DBG_INDENT}"
       fi
     done
     unset i

     DBG_INDENT_FUNC down
     DBG_ECHO "$DBG_INDENT}"


########################################################################
#   End Shell Startup Debug
########################################################################
