#!/bin/zsh
# -*- shell-script -*-
# /etc/zsh/zprofile: system-wide .zprofile file for zsh(1).
#
# This file is sourced only for login shells (i.e. shells
# invoked with "-" as the first character of argv[0], and
# shells invoked with the -l flag.)
#
# Global Order: zshenv, zprofile, zshrc, zlogin

########################################################################
#   Begin Shell Startup Debug
########################################################################

    MY_NAME="/etc/zsh/zprofile"
    DBG_ECHO "$DBG_INDENT$MY_NAME{"

    DBG_ECHO "$DBG_INDENT}"

########################################################################
#   End Shell Startup Debug
########################################################################
